// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_types.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const activityTypeNameInUse = `-- name: ActivityTypeNameInUse :one
SELECT EXISTS(
    SELECT 1
    FROM activity_types
    WHERE user_id = $1
      AND lower(name) = lower($2)
      AND id <> $3
)::boolean
`

type ActivityTypeNameInUseParams struct {
	UserID    uuid.UUID
	Name      string
	ExcludeID uuid.UUID
}

func (q *Queries) ActivityTypeNameInUse(ctx context.Context, arg ActivityTypeNameInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, activityTypeNameInUse, arg.UserID, arg.Name, arg.ExcludeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countActivityTypeSessions = `-- name: CountActivityTypeSessions :one
SELECT count(*)::bigint FROM sessions WHERE user_id = $1 AND activity_type_id = $2
`

type CountActivityTypeSessionsParams struct {
	UserID         uuid.UUID
	ActivityTypeID *uuid.UUID
}

func (q *Queries) CountActivityTypeSessions(ctx context.Context, arg CountActivityTypeSessionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityTypeSessions, arg.UserID, arg.ActivityTypeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteActivityType = `-- name: DeleteActivityType :exec
DELETE FROM activity_types WHERE user_id = $1 AND id = $2
`

type DeleteActivityTypeParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteActivityType(ctx context.Context, arg DeleteActivityTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityType, arg.UserID, arg.ID)
	return err
}

const getActivityType = `-- name: GetActivityType :one
SELECT id, name, color
FROM activity_types
WHERE user_id = $1 AND id = $2
`

type GetActivityTypeParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetActivityTypeRow struct {
	ID    uuid.UUID
	Name  string
	Color string
}

func (q *Queries) GetActivityType(ctx context.Context, arg GetActivityTypeParams) (GetActivityTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getActivityType, arg.UserID, arg.ID)
	var i GetActivityTypeRow
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const insertActivityType = `-- name: InsertActivityType :one
INSERT INTO activity_types (id, user_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color
`

type InsertActivityTypeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Color  string
}

type InsertActivityTypeRow struct {
	ID    uuid.UUID
	Name  string
	Color string
}

func (q *Queries) InsertActivityType(ctx context.Context, arg InsertActivityTypeParams) (InsertActivityTypeRow, error) {
	row := q.db.QueryRowContext(ctx, insertActivityType,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
	)
	var i InsertActivityTypeRow
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const listActivityTypes = `-- name: ListActivityTypes :many
SELECT id, name, color
FROM activity_types
WHERE user_id = $1
ORDER BY lower(name) ASC
`

type ListActivityTypesRow struct {
	ID    uuid.UUID
	Name  string
	Color string
}

func (q *Queries) ListActivityTypes(ctx context.Context, userID uuid.UUID) ([]ListActivityTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityTypesRow
	for rows.Next() {
		var i ListActivityTypesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityType = `-- name: UpdateActivityType :one
UPDATE activity_types
SET name = $3,
    color = $4,
    updated_at = now()
WHERE user_id = $1 AND id = $2
RETURNING id, name, color
`

type UpdateActivityTypeParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Name   string
	Color  string
}

type UpdateActivityTypeRow struct {
	ID    uuid.UUID
	Name  string
	Color string
}

func (q *Queries) UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) (UpdateActivityTypeRow, error) {
	row := q.db.QueryRowContext(ctx, updateActivityType,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Color,
	)
	var i UpdateActivityTypeRow
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}
