// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentread.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAgentLiveSession = `-- name: GetAgentLiveSession :one
SELECT
    s.id,
    s.project_id,
    p.name AS project_name,
    s.note,
    s.ticket_id,
    s.activity_type_id,
    COALESCE(a.name, '') AS activity_type_name,
    s.status,
    s.started_at,
    s.ended_at,
    s.target_duration_ms
FROM sessions s
JOIN projects p ON p.id = s.project_id AND p.user_id = s.user_id
LEFT JOIN activity_types a ON a.id = s.activity_type_id AND a.user_id = s.user_id
WHERE s.user_id = $1 AND s.status = 'active'
`

type GetAgentLiveSessionRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ProjectName      string
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	ActivityTypeName string
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) GetAgentLiveSession(ctx context.Context, userID uuid.UUID) (GetAgentLiveSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentLiveSession, userID)
	var i GetAgentLiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.ActivityTypeName,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TargetDurationMs,
	)
	return i, err
}

const listAgentProjects = `-- name: ListAgentProjects :many

SELECT id, name, color, code, progress_percent, archived
FROM projects
WHERE user_id = $1
  AND (archived = FALSE OR $2::boolean = TRUE)
ORDER BY name ASC
`

type ListAgentProjectsParams struct {
	UserID          uuid.UUID
	IncludeArchived bool
}

type ListAgentProjectsRow struct {
	ID              uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

// Read models for the local MCP. Every statement is scoped by user_id.
// Do not select password_hash, token_hash, code_hash, or avatar bytes.
func (q *Queries) ListAgentProjects(ctx context.Context, arg ListAgentProjectsParams) ([]ListAgentProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentProjects, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentProjectsRow
	for rows.Next() {
		var i ListAgentProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Code,
			&i.ProgressPercent,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT
    s.id,
    s.project_id,
    p.name AS project_name,
    s.note,
    s.ticket_id,
    s.activity_type_id,
    COALESCE(a.name, '') AS activity_type_name,
    s.status,
    s.started_at,
    s.ended_at,
    s.target_duration_ms
FROM sessions s
JOIN projects p ON p.id = s.project_id AND p.user_id = s.user_id
LEFT JOIN activity_types a ON a.id = s.activity_type_id AND a.user_id = s.user_id
WHERE s.user_id = $1
  AND (
    $2::boolean = FALSE
    OR s.project_id = $3::uuid
  )
  AND (
    $4::boolean = FALSE
    OR s.status = $5
  )
  AND (
    $6::boolean = FALSE
    OR s.ended_at IS NULL
    OR s.ended_at > $7::timestamptz
  )
  AND (
    $8::boolean = FALSE
    OR s.started_at < $9::timestamptz
  )
ORDER BY s.started_at DESC, s.id DESC
LIMIT $10::int
`

type ListAgentSessionsParams struct {
	UserID        uuid.UUID
	FilterProject bool
	ProjectID     uuid.UUID
	FilterStatus  bool
	Status        string
	FilterFrom    bool
	FromTs        time.Time
	FilterTo      bool
	ToTs          time.Time
	Lim           int32
}

type ListAgentSessionsRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ProjectName      string
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	ActivityTypeName string
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]ListAgentSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessions,
		arg.UserID,
		arg.FilterProject,
		arg.ProjectID,
		arg.FilterStatus,
		arg.Status,
		arg.FilterFrom,
		arg.FromTs,
		arg.FilterTo,
		arg.ToTs,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSessionsRow
	for rows.Next() {
		var i ListAgentSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Note,
			&i.TicketID,
			&i.ActivityTypeID,
			&i.ActivityTypeName,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.TargetDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsInWindow = `-- name: ListAgentSessionsInWindow :many
SELECT
    s.id,
    s.project_id,
    p.name AS project_name,
    s.note,
    s.ticket_id,
    s.activity_type_id,
    COALESCE(a.name, '') AS activity_type_name,
    s.status,
    s.started_at,
    s.ended_at,
    s.target_duration_ms
FROM sessions s
JOIN projects p ON p.id = s.project_id AND p.user_id = s.user_id
LEFT JOIN activity_types a ON a.id = s.activity_type_id AND a.user_id = s.user_id
WHERE s.user_id = $1
  AND s.started_at < $2::timestamptz
  AND (s.ended_at IS NULL OR s.ended_at > $3::timestamptz)
ORDER BY s.started_at ASC, s.id ASC
LIMIT 10001
`

type ListAgentSessionsInWindowParams struct {
	UserID uuid.UUID
	ToTs   time.Time
	FromTs time.Time
}

type ListAgentSessionsInWindowRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ProjectName      string
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	ActivityTypeName string
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) ListAgentSessionsInWindow(ctx context.Context, arg ListAgentSessionsInWindowParams) ([]ListAgentSessionsInWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessionsInWindow, arg.UserID, arg.ToTs, arg.FromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSessionsInWindowRow
	for rows.Next() {
		var i ListAgentSessionsInWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Note,
			&i.TicketID,
			&i.ActivityTypeID,
			&i.ActivityTypeName,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.TargetDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
