// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAuthTokenByHash = `-- name: DeleteAuthTokenByHash :exec
DELETE FROM auth_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteAuthTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthTokenByHash, tokenHash)
	return err
}

const deleteAuthTokensByUser = `-- name: DeleteAuthTokensByUser :exec
DELETE FROM auth_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAuthTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAuthTokensByUser, userID)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :execrows
DELETE FROM auth_tokens WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherAuthTokens = `-- name: DeleteOtherAuthTokens :exec
DELETE FROM auth_tokens WHERE user_id = $1 AND token_hash <> $2
`

type DeleteOtherAuthTokensParams struct {
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) DeleteOtherAuthTokens(ctx context.Context, arg DeleteOtherAuthTokensParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherAuthTokens, arg.UserID, arg.TokenHash)
	return err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, token_hash, expires_at
FROM auth_tokens
WHERE token_hash = $1
`

type GetAuthTokenByHashRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (GetAuthTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthTokenByHash, tokenHash)
	var i GetAuthTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAuthToken = `-- name: InsertAuthToken :exec
INSERT INTO auth_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertAuthTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
