// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_challenges.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteEmailChallenge = `-- name: DeleteEmailChallenge :exec
DELETE FROM email_challenges WHERE email = $1 AND purpose = $2
`

type DeleteEmailChallengeParams struct {
	Email   string
	Purpose string
}

func (q *Queries) DeleteEmailChallenge(ctx context.Context, arg DeleteEmailChallengeParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailChallenge, arg.Email, arg.Purpose)
	return err
}

const getEmailChallenge = `-- name: GetEmailChallenge :one
SELECT email, purpose, code_hash, expires_at, attempt_count, sent_at, send_count, send_window_start
FROM email_challenges
WHERE email = $1 AND purpose = $2
`

type GetEmailChallengeParams struct {
	Email   string
	Purpose string
}

func (q *Queries) GetEmailChallenge(ctx context.Context, arg GetEmailChallengeParams) (EmailChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailChallenge, arg.Email, arg.Purpose)
	var i EmailChallenge
	err := row.Scan(
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.SentAt,
		&i.SendCount,
		&i.SendWindowStart,
	)
	return i, err
}

const incrementChallengeAttempts = `-- name: IncrementChallengeAttempts :one
UPDATE email_challenges
SET attempt_count = attempt_count + 1
WHERE email = $1 AND purpose = $2
RETURNING attempt_count
`

type IncrementChallengeAttemptsParams struct {
	Email   string
	Purpose string
}

func (q *Queries) IncrementChallengeAttempts(ctx context.Context, arg IncrementChallengeAttemptsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrementChallengeAttempts, arg.Email, arg.Purpose)
	var attempt_count int32
	err := row.Scan(&attempt_count)
	return attempt_count, err
}

const upsertEmailChallenge = `-- name: UpsertEmailChallenge :exec
INSERT INTO email_challenges (
    email, purpose, code_hash, expires_at, attempt_count, sent_at, send_count, send_window_start
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (email, purpose) DO UPDATE SET
    code_hash = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempt_count = EXCLUDED.attempt_count,
    sent_at = EXCLUDED.sent_at,
    send_count = EXCLUDED.send_count,
    send_window_start = EXCLUDED.send_window_start
`

type UpsertEmailChallengeParams struct {
	Email           string
	Purpose         string
	CodeHash        string
	ExpiresAt       time.Time
	AttemptCount    int32
	SentAt          time.Time
	SendCount       int32
	SendWindowStart time.Time
}

func (q *Queries) UpsertEmailChallenge(ctx context.Context, arg UpsertEmailChallengeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmailChallenge,
		arg.Email,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.AttemptCount,
		arg.SentAt,
		arg.SendCount,
		arg.SendWindowStart,
	)
	return err
}
