// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_challenges.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailChallenge = `-- name: ConsumeEmailChallenge :execrows
DELETE FROM email_challenges
WHERE email = $1 AND purpose = $2 AND code_hash = $3
`

type ConsumeEmailChallengeParams struct {
	Email    string
	Purpose  string
	CodeHash string
}

// Deletes the challenge only while it still holds the code that was compared.
func (q *Queries) ConsumeEmailChallenge(ctx context.Context, arg ConsumeEmailChallengeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeEmailChallenge, arg.Email, arg.Purpose, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEmailChallengesExpiredBefore = `-- name: DeleteEmailChallengesExpiredBefore :execrows
DELETE FROM email_challenges WHERE expires_at < $1
`

func (q *Queries) DeleteEmailChallengesExpiredBefore(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmailChallengesExpiredBefore, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEmailChallenge = `-- name: GetEmailChallenge :one
SELECT email, purpose, code_hash, expires_at, attempt_count, sent_at, send_count, send_window_start, user_id
FROM email_challenges
WHERE email = $1 AND purpose = $2
`

type GetEmailChallengeParams struct {
	Email   string
	Purpose string
}

func (q *Queries) GetEmailChallenge(ctx context.Context, arg GetEmailChallengeParams) (EmailChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailChallenge, arg.Email, arg.Purpose)
	var i EmailChallenge
	err := row.Scan(
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.SentAt,
		&i.SendCount,
		&i.SendWindowStart,
		&i.UserID,
	)
	return i, err
}

const reserveChallengeGuess = `-- name: ReserveChallengeGuess :one
UPDATE email_challenges
SET attempt_count = attempt_count + 1
WHERE email = $1
  AND purpose = $2
  AND user_id IS NOT DISTINCT FROM $3::uuid
  AND attempt_count < $4::int
RETURNING email, purpose, code_hash, expires_at, attempt_count, sent_at, send_count, send_window_start, user_id
`

type ReserveChallengeGuessParams struct {
	Email       string
	Purpose     string
	UserID      uuid.NullUUID
	MaxAttempts int32
}

// Takes one guess atomically before the code is compared. No row when the challenge
// is missing, bound to another account, or already out of guesses.
func (q *Queries) ReserveChallengeGuess(ctx context.Context, arg ReserveChallengeGuessParams) (EmailChallenge, error) {
	row := q.db.QueryRowContext(ctx, reserveChallengeGuess,
		arg.Email,
		arg.Purpose,
		arg.UserID,
		arg.MaxAttempts,
	)
	var i EmailChallenge
	err := row.Scan(
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.SentAt,
		&i.SendCount,
		&i.SendWindowStart,
		&i.UserID,
	)
	return i, err
}

const upsertEmailChallenge = `-- name: UpsertEmailChallenge :exec
INSERT INTO email_challenges (
    email, purpose, code_hash, expires_at, attempt_count, sent_at, send_count, send_window_start, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (email, purpose) DO UPDATE SET
    code_hash = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempt_count = EXCLUDED.attempt_count,
    sent_at = EXCLUDED.sent_at,
    send_count = EXCLUDED.send_count,
    send_window_start = EXCLUDED.send_window_start,
    user_id = EXCLUDED.user_id
`

type UpsertEmailChallengeParams struct {
	Email           string
	Purpose         string
	CodeHash        string
	ExpiresAt       time.Time
	AttemptCount    int32
	SentAt          time.Time
	SendCount       int32
	SendWindowStart time.Time
	UserID          uuid.NullUUID
}

func (q *Queries) UpsertEmailChallenge(ctx context.Context, arg UpsertEmailChallengeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmailChallenge,
		arg.Email,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.AttemptCount,
		arg.SentAt,
		arg.SendCount,
		arg.SendWindowStart,
		arg.UserID,
	)
	return err
}
