// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Profile struct {
	UserID      uuid.UUID
	DisplayName string
	Handle      string
	AvatarUrl   sql.NullString
}

type Project struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityType     sql.NullString
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

type User struct {
	ID uuid.UUID
}
