// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prefs.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPrefs = `-- name: GetPrefs :one
SELECT daily_target_ms, default_project_id
FROM user_prefs
WHERE user_id = $1
`

type GetPrefsRow struct {
	DailyTargetMs    sql.NullInt64
	DefaultProjectID uuid.NullUUID
}

func (q *Queries) GetPrefs(ctx context.Context, userID uuid.UUID) (GetPrefsRow, error) {
	row := q.db.QueryRowContext(ctx, getPrefs, userID)
	var i GetPrefsRow
	err := row.Scan(&i.DailyTargetMs, &i.DefaultProjectID)
	return i, err
}

const upsertPrefs = `-- name: UpsertPrefs :exec
INSERT INTO user_prefs (user_id, daily_target_ms, default_project_id, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
SET daily_target_ms = EXCLUDED.daily_target_ms,
    default_project_id = EXCLUDED.default_project_id,
    updated_at = now()
`

type UpsertPrefsParams struct {
	UserID           uuid.UUID
	DailyTargetMs    sql.NullInt64
	DefaultProjectID uuid.NullUUID
}

func (q *Queries) UpsertPrefs(ctx context.Context, arg UpsertPrefsParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrefs, arg.UserID, arg.DailyTargetMs, arg.DefaultProjectID)
	return err
}
