// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const firstUserID = `-- name: FirstUserID :one
SELECT id FROM users ORDER BY id LIMIT 1
`

func (q *Queries) FirstUserID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, firstUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProfile = `-- name: GetProfile :one
SELECT display_name, handle, avatar_url
FROM profiles
WHERE user_id = $1
`

type GetProfileRow struct {
	DisplayName string
	Handle      string
	AvatarUrl   sql.NullString
}

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(&i.DisplayName, &i.Handle, &i.AvatarUrl)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const insertProfile = `-- name: InsertProfile :exec
INSERT INTO profiles (user_id, display_name, handle, avatar_url)
VALUES ($1, $2, $3, $4)
`

type InsertProfileParams struct {
	UserID      uuid.UUID
	DisplayName string
	Handle      string
	AvatarUrl   sql.NullString
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, username, password_hash) VALUES ($1, $2, $3)
`

type InsertUserParams struct {
	ID           uuid.UUID
	Username     sql.NullString
	PasswordHash sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const setUserCredentials = `-- name: SetUserCredentials :exec
UPDATE users
SET username = $2, password_hash = $3
WHERE id = $1
`

type SetUserCredentialsParams struct {
	ID           uuid.UUID
	Username     sql.NullString
	PasswordHash sql.NullString
}

func (q *Queries) SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, setUserCredentials, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const usernameInUse = `-- name: UsernameInUse :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE username = $1 AND id <> $2
)::boolean
`

type UsernameInUseParams struct {
	Username sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UsernameInUse(ctx context.Context, arg UsernameInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, usernameInUse, arg.Username, arg.ID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
