// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const codeInUse = `-- name: CodeInUse :one
SELECT EXISTS(
    SELECT 1
    FROM projects
    WHERE user_id = $1
      AND code IS NOT NULL
      AND lower(code) = lower($2)
      AND id <> $3
)::boolean
`

type CodeInUseParams struct {
	UserID    uuid.UUID
	Code      string
	ExcludeID uuid.UUID
}

func (q *Queries) CodeInUse(ctx context.Context, arg CodeInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, codeInUse, arg.UserID, arg.Code, arg.ExcludeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveProjects = `-- name: CountActiveProjects :one
SELECT count(*)::bigint FROM projects WHERE user_id = $1 AND archived = FALSE
`

func (q *Queries) CountActiveProjects(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveProjects, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProjectSessions = `-- name: CountProjectSessions :one
SELECT count(*)::bigint FROM sessions WHERE user_id = $1 AND project_id = $2
`

type CountProjectSessionsParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) CountProjectSessions(ctx context.Context, arg CountProjectSessionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectSessions, arg.UserID, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE user_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.UserID, arg.ID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, color, code, progress_percent, archived
FROM projects
WHERE user_id = $1 AND id = $2
`

type GetProjectParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetProjectRow struct {
	ID              uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.UserID, arg.ID)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Code,
		&i.ProgressPercent,
		&i.Archived,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (id, user_id, name, color, code, progress_percent, archived)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, color, code, progress_percent, archived
`

type InsertProjectParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

type InsertProjectRow struct {
	ID              uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (InsertProjectRow, error) {
	row := q.db.QueryRowContext(ctx, insertProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Code,
		arg.ProgressPercent,
		arg.Archived,
	)
	var i InsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Code,
		&i.ProgressPercent,
		&i.Archived,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, color, code, progress_percent, archived
FROM projects
WHERE user_id = $1
  AND (archived = FALSE OR $2::boolean = TRUE)
ORDER BY name ASC
`

type ListProjectsParams struct {
	UserID          uuid.UUID
	IncludeArchived bool
}

type ListProjectsRow struct {
	ID              uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Code,
			&i.ProgressPercent,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3,
    color = $4,
    code = $5,
    progress_percent = $6,
    archived = $7,
    updated_at = now()
WHERE user_id = $1 AND id = $2
RETURNING id, name, color, code, progress_percent, archived
`

type UpdateProjectParams struct {
	UserID          uuid.UUID
	ID              uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

type UpdateProjectRow struct {
	ID              uuid.UUID
	Name            string
	Color           string
	Code            sql.NullString
	ProgressPercent sql.NullInt32
	Archived        bool
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Code,
		arg.ProgressPercent,
		arg.Archived,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Code,
		&i.ProgressPercent,
		&i.Archived,
	)
	return i, err
}
