// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE user_id = $1 AND id = $2
`

type DeleteSessionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.UserID, arg.ID)
	return err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, project_id, note, ticket_id, activity_type_id, tags, status,
       started_at, ended_at, paused_ms, paused_at, target_duration_ms
FROM sessions
WHERE user_id = $1 AND status IN ('active', 'paused')
`

type GetLiveSessionRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) GetLiveSession(ctx context.Context, userID uuid.UUID) (GetLiveSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getLiveSession, userID)
	var i GetLiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Tags,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.PausedMs,
		&i.PausedAt,
		&i.TargetDurationMs,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, note, ticket_id, activity_type_id, tags, status,
       started_at, ended_at, paused_ms, paused_at, target_duration_ms
FROM sessions
WHERE user_id = $1 AND id = $2
`

type GetSessionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetSessionRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.UserID, arg.ID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Tags,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.PausedMs,
		&i.PausedAt,
		&i.TargetDurationMs,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    id, user_id, project_id, note, ticket_id, activity_type_id, tags, status,
    started_at, ended_at, paused_ms, paused_at, target_duration_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id, project_id, note, ticket_id, activity_type_id, tags, status,
          started_at, ended_at, paused_ms, paused_at, target_duration_ms
`

type InsertSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

type InsertSessionRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Note,
		arg.TicketID,
		arg.ActivityTypeID,
		arg.Tags,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.PausedMs,
		arg.PausedAt,
		arg.TargetDurationMs,
	)
	var i InsertSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Tags,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.PausedMs,
		&i.PausedAt,
		&i.TargetDurationMs,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, project_id, note, ticket_id, activity_type_id, tags, status,
       started_at, ended_at, paused_ms, paused_at, target_duration_ms
FROM sessions
WHERE user_id = $1
  AND (
    $2::boolean = FALSE
    OR ($3::boolean AND status = 'active')
    OR ($4::boolean AND status = 'paused')
    OR ($5::boolean AND status = 'stopped')
  )
ORDER BY started_at DESC
LIMIT NULLIF($6::int, 0)
`

type ListSessionsParams struct {
	UserID         uuid.UUID
	FilterStatuses bool
	WantActive     bool
	WantPaused     bool
	WantStopped    bool
	Lim            int32
}

type ListSessionsRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions,
		arg.UserID,
		arg.FilterStatuses,
		arg.WantActive,
		arg.WantPaused,
		arg.WantStopped,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Note,
			&i.TicketID,
			&i.ActivityTypeID,
			&i.Tags,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.PausedMs,
			&i.PausedAt,
			&i.TargetDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET project_id = $3,
    note = $4,
    ticket_id = $5,
    activity_type_id = $6,
    tags = $7,
    status = $8,
    started_at = $9,
    ended_at = $10,
    paused_ms = $11,
    paused_at = $12,
    target_duration_ms = $13
WHERE user_id = $1 AND id = $2
RETURNING id, project_id, note, ticket_id, activity_type_id, tags, status,
          started_at, ended_at, paused_ms, paused_at, target_duration_ms
`

type UpdateSessionParams struct {
	UserID           uuid.UUID
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

type UpdateSessionRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Note             string
	TicketID         sql.NullString
	ActivityTypeID   *uuid.UUID
	Tags             json.RawMessage
	Status           string
	StartedAt        time.Time
	EndedAt          sql.NullTime
	PausedMs         int64
	PausedAt         sql.NullTime
	TargetDurationMs sql.NullInt64
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (UpdateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.UserID,
		arg.ID,
		arg.ProjectID,
		arg.Note,
		arg.TicketID,
		arg.ActivityTypeID,
		arg.Tags,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.PausedMs,
		arg.PausedAt,
		arg.TargetDurationMs,
	)
	var i UpdateSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Tags,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.PausedMs,
		&i.PausedAt,
		&i.TargetDurationMs,
	)
	return i, err
}
