// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE user_id = $1 AND id = $2
`

type DeleteSessionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.UserID, arg.ID)
	return err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, project_id, note, ticket_id, activity_type_id, status,
       started_at, ended_at
FROM sessions
WHERE user_id = $1 AND status = 'active'
`

type GetLiveSessionRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) GetLiveSession(ctx context.Context, userID uuid.UUID) (GetLiveSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getLiveSession, userID)
	var i GetLiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, note, ticket_id, activity_type_id, status,
       started_at, ended_at
FROM sessions
WHERE user_id = $1 AND id = $2
`

type GetSessionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetSessionRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.UserID, arg.ID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    id, user_id, project_id, note, ticket_id, activity_type_id, status,
    started_at, ended_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9
)
RETURNING id, project_id, note, ticket_id, activity_type_id, status,
          started_at, ended_at
`

type InsertSessionParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

type InsertSessionRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Note,
		arg.TicketID,
		arg.ActivityTypeID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i InsertSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, project_id, note, ticket_id, activity_type_id, status,
       started_at, ended_at
FROM sessions
WHERE user_id = $1
  AND (
    $2::boolean = FALSE
    OR ($3::boolean AND status = 'active')
    OR ($4::boolean AND status = 'stopped')
  )
  AND (
    $5::boolean = FALSE
    OR started_at < $6::timestamptz
    OR (
      started_at = $6::timestamptz
      AND id < $7::uuid
    )
  )
ORDER BY started_at DESC, id DESC
LIMIT $8::int
`

type ListSessionsParams struct {
	UserID         uuid.UUID
	FilterStatuses bool
	WantActive     bool
	WantStopped    bool
	UseCursor      bool
	CursorStarted  time.Time
	CursorID       uuid.UUID
	Lim            int32
}

type ListSessionsRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions,
		arg.UserID,
		arg.FilterStatuses,
		arg.WantActive,
		arg.WantStopped,
		arg.UseCursor,
		arg.CursorStarted,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Note,
			&i.TicketID,
			&i.ActivityTypeID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoppedSessionsStartedBetween = `-- name: ListStoppedSessionsStartedBetween :many
SELECT id, project_id, note, ticket_id, activity_type_id, status,
       started_at, ended_at
FROM sessions
WHERE user_id = $1
  AND status = 'stopped'
  AND started_at >= $2::timestamptz
  AND started_at < $3::timestamptz
ORDER BY started_at, id
`

type ListStoppedSessionsStartedBetweenParams struct {
	UserID uuid.UUID
	FromAt time.Time
	ToAt   time.Time
}

type ListStoppedSessionsStartedBetweenRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) ListStoppedSessionsStartedBetween(ctx context.Context, arg ListStoppedSessionsStartedBetweenParams) ([]ListStoppedSessionsStartedBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, listStoppedSessionsStartedBetween, arg.UserID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoppedSessionsStartedBetweenRow
	for rows.Next() {
		var i ListStoppedSessionsStartedBetweenRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Note,
			&i.TicketID,
			&i.ActivityTypeID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionSession = `-- name: TransitionSession :one
UPDATE sessions
SET project_id = $3,
    note = $4,
    ticket_id = $5,
    activity_type_id = $6,
    status = $7,
    started_at = $8,
    ended_at = $9
WHERE user_id = $1 AND id = $2 AND status = $10
RETURNING id, project_id, note, ticket_id, activity_type_id, status,
          started_at, ended_at
`

type TransitionSessionParams struct {
	UserID         uuid.UUID
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
	Status_2       string
}

type TransitionSessionRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) TransitionSession(ctx context.Context, arg TransitionSessionParams) (TransitionSessionRow, error) {
	row := q.db.QueryRowContext(ctx, transitionSession,
		arg.UserID,
		arg.ID,
		arg.ProjectID,
		arg.Note,
		arg.TicketID,
		arg.ActivityTypeID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status_2,
	)
	var i TransitionSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET project_id = $3,
    note = $4,
    ticket_id = $5,
    activity_type_id = $6,
    status = $7,
    started_at = $8,
    ended_at = $9
WHERE user_id = $1 AND id = $2
RETURNING id, project_id, note, ticket_id, activity_type_id, status,
          started_at, ended_at
`

type UpdateSessionParams struct {
	UserID         uuid.UUID
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

type UpdateSessionRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Note           string
	TicketID       sql.NullString
	ActivityTypeID *uuid.UUID
	Status         string
	StartedAt      time.Time
	EndedAt        sql.NullTime
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (UpdateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.UserID,
		arg.ID,
		arg.ProjectID,
		arg.Note,
		arg.TicketID,
		arg.ActivityTypeID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i UpdateSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Note,
		&i.TicketID,
		&i.ActivityTypeID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}
